//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcademiaEntities : DbContext
    {
        public AcademiaEntities()
            : base("name=AcademiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<alumnos_inscripciones> alumnos_inscripciones { get; set; }
        public DbSet<comisione> comisiones { get; set; }
        public DbSet<curso> cursos { get; set; }
        public DbSet<docentes_cursos> docentes_cursos { get; set; }
        public DbSet<especialidade> especialidades { get; set; }
        public DbSet<materia> materias { get; set; }
        public DbSet<modulo> modulos { get; set; }
        public DbSet<modulos_usuarios> modulos_usuarios { get; set; }
        public DbSet<persona> personas { get; set; }
        public DbSet<plane> planes { get; set; }
        public DbSet<usuario> usuarios { get; set; }
    }
}
