//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class especialidade
    {
        public especialidade()
        {
            this.planes = new HashSet<plane>();
        }
    
        public int id_especialidad { get; set; }
        public string desc_especialidad { get; set; }
    
        public virtual ICollection<plane> planes { get; set; }
    }
}
