//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.modulos_usuarios = new HashSet<modulos_usuarios>();
        }
    
        public int id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string clave { get; set; }
        public bool habilitado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string email { get; set; }
        public Nullable<bool> cambia_clave { get; set; }
        public Nullable<int> id_persona { get; set; }
    
        public virtual ICollection<modulos_usuarios> modulos_usuarios { get; set; }
        public virtual persona persona { get; set; }
    }
}
